apiVersion: v1
kind: ConfigMap
metadata:
  name: dmproadmap-config
data:
  RAILS_LOG_LEVEL: 'info'
  RAILS_LOG_TO_STDOUT: 'true'
  RAILS_SERVE_STATIC_FILES: 'true'
  RAILS_MAX_THREADS: '5'
  WEB_CONCURRENCY: '2'
  PORT: '3000'
  DMPROADMAP_HOST: 'localhost' # Change this to your actual domain
  WICKED_PDF_PATH: '/usr/local/bin/wkhtmltopdf'
  DB_ADAPTER: 'postgresql'
  DB_HOST: 'dmproadmap-postgres' # This will be your PostgreSQL service name
  DB_PORT: '5432'
  DB_POOL_SIZE: '16'
  DB_NAME: 'roadmap'
  DRAGONFLY_AWS: 'false' # Set to true if using S3 for storage
  DOMAIN: 'app'
