FROM ruby:3.3.2

# Install dependencies

RUN apt-get update -qq && \
apt-get install -y \
build-essential \
git \
libgmp3-dev \
libpq-dev \
postgresql-client \
gettext \
certbot \
wget \
curl \
vim \
ack

ARG INSTALL_PATH=/usr/src/app
ENV INSTALL_PATH=$INSTALL_PATH
ENV BUNDLE_PATH=/bundle/ \
  BUNDLE_BIN=/bundle/bin \
  GEM_HOME=/bundle
ENV Path="${BUNDLE_BIN}:${PATH}"

WORKDIR $INSTALL_PATH

RUN touch ~/.bashrc
RUN echo "alias rails='bundle exec rails'" >> ~/.bashrc
RUN echo "export EDITOR=vim" >> ~/.bashrc
RUN echo "alias racp='rails assets:clobber assets:precompile'" >> ~/.bashrc

# install yarn+node from packages
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get install -y nodejs
RUN apt-get update && apt-get install -y yarn
RUN wget --quiet https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz && \
  tar vxf wkhtmltox-0.12.3_linux-generic-amd64.tar.xz && \
  cp wkhtmltox/bin/wk* /usr/local/bin/ && \
  rm -rf wkhtmltox

WORKDIR $INSTALL_PATH
# Install gems
COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle config set without 'mysql thin' && bundle install --jobs 20 --retry 5

# Install yarn packages
COPY package.json yarn.lock ./
RUN yarn install

COPY  config/database.yml.sample  config/database.yml
COPY  config/initializers/contact_us.rb.example config/initializers/contact_us.rb
COPY  config/initializers/wicked_pdf.rb.example config/initializers/wicked_pdf.rb

# Precompile assets
RUN RAILS_ENV=production SECRET_KEY_BASE=57d06d315e922b1804c81c204169bbbab77177312d3ef2f4e53464a6da5784953bbd6d7143f5eb87d05bfd63baccc3067f95390c9a46da05c34aa45db2ff1c15 \
 bundle exec rails assets:precompile

# Copy application code
COPY . .


# expose correct port
EXPOSE 3000

# Start the server
CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]