apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dmproadmap-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: dmproadmap.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dmproadmap
                port:
                  number: 80
